pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-rubygems
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Rubygems
  desc: Publish ruby gems to a Rubygems server
  type: publish
  image: plugins/drone-rubygems
  labels:
    - ruby
    - gem
    - rubygems
